import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-legal-settlement-fund-distribution-reconciliation",
  "engine": "recovery",
  "title": "Legal Settlement Fund Distribution Reconciliation",
  "shortTitle": "Legal Settlement Fund Distribution Reconciliation",
  "tagline": "Calculate and reconcile claimant distributions, liens, fees, returned payments, and residual settlement funds.",
  "industry": "Legal Financial Operations",
  "buyer": "Claims administrators, law firms, and settlement trustees",
  "uiPort": 4728,
  "apiPort": 5728,
  "accent": "#4338ca",
  "currency": "USD",
  "primaryOutcome": "Legal Settlement Fund Distribution Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect settlement agreements, claimant eligibility, claim forms, damages, allocation formulas, liens, fees, taxes, distributions, returned payments, and residual funds in one accountable workflow. Calculate and reconcile claimant distributions, liens, fees, returned payments, and residual settlement funds.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Legal Settlement Fund Distribution Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("settlement-term-library","LSF01","Settlement term library","Execute settlement term library using settlement agreements, claimant eligibility, claim forms, damages, allocation formulas, liens, fees, taxes, distributions, returned payments, and residual funds.","Produce a governed settlement term library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Settlement / Claimant Population","text","Settlement / Claimant Population · Standard Case"],["caseReference","Settlement term library Reference","text","LSF01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1676250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2028263],["domainDriver","Distribution Class","select","Class member",["Class member","Lienholder","Counsel fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Settlement term library case","Claimant identity registry case","Eligibility validation case","Claim form ingestion case","Damage category calculation case"]}),
feature("claimant-identity-registry","LSF02","Claimant identity registry","Execute claimant identity registry using settlement agreements, claimant eligibility, claim forms, damages, allocation formulas, liens, fees, taxes, distributions, returned payments, and residual funds.","Produce a governed claimant identity registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Settlement / Claimant Population","text","Settlement / Claimant Population · Standard Case"],["caseReference","Claimant identity registry Reference","text","LSF02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1676250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2028263],["domainDriver","Distribution Class","select","Class member",["Class member","Lienholder","Counsel fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Settlement term library case","Claimant identity registry case","Eligibility validation case","Claim form ingestion case","Damage category calculation case"]}),
feature("eligibility-validation","LSF03","Eligibility validation","Execute eligibility validation using settlement agreements, claimant eligibility, claim forms, damages, allocation formulas, liens, fees, taxes, distributions, returned payments, and residual funds.","Produce a governed eligibility validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Settlement / Claimant Population","text","Settlement / Claimant Population · Standard Case"],["caseReference","Eligibility validation Reference","text","LSF03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1676250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2028263],["domainDriver","Distribution Class","select","Class member",["Class member","Lienholder","Counsel fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Settlement term library case","Claimant identity registry case","Eligibility validation case","Claim form ingestion case","Damage category calculation case"]}),
feature("claim-form-ingestion","LSF04","Claim form ingestion","Execute claim form ingestion using settlement agreements, claimant eligibility, claim forms, damages, allocation formulas, liens, fees, taxes, distributions, returned payments, and residual funds.","Produce a governed claim form ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Settlement / Claimant Population","text","Settlement / Claimant Population · Standard Case"],["caseReference","Claim form ingestion Reference","text","LSF04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1676250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2028263],["domainDriver","Distribution Class","select","Class member",["Class member","Lienholder","Counsel fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Settlement term library case","Claimant identity registry case","Eligibility validation case","Claim form ingestion case","Damage category calculation case"]}),
feature("damage-category-calculation","LSF05","Damage category calculation","Execute damage category calculation using settlement agreements, claimant eligibility, claim forms, damages, allocation formulas, liens, fees, taxes, distributions, returned payments, and residual funds.","Produce a governed damage category calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Settlement / Claimant Population","text","Settlement / Claimant Population · Standard Case"],["caseReference","Damage category calculation Reference","text","LSF05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1676250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2028263],["domainDriver","Distribution Class","select","Class member",["Class member","Lienholder","Counsel fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Settlement term library case","Claimant identity registry case","Eligibility validation case","Claim form ingestion case","Damage category calculation case"]}),
feature("pro-rata-allocation","LSF06","Pro-rata allocation","Execute pro-rata allocation using settlement agreements, claimant eligibility, claim forms, damages, allocation formulas, liens, fees, taxes, distributions, returned payments, and residual funds.","Produce a governed pro-rata allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Settlement / Claimant Population","text","Settlement / Claimant Population · Standard Case"],["caseReference","Pro-rata allocation Reference","text","LSF06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1676250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2028263],["domainDriver","Distribution Class","select","Class member",["Class member","Lienholder","Counsel fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Settlement term library case","Claimant identity registry case","Eligibility validation case","Claim form ingestion case","Damage category calculation case"]}),
feature("lien-holdback-control","LSF07","Lien holdback control","Execute lien holdback control using settlement agreements, claimant eligibility, claim forms, damages, allocation formulas, liens, fees, taxes, distributions, returned payments, and residual funds.","Produce a governed lien holdback control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Settlement / Claimant Population","text","Settlement / Claimant Population · Standard Case"],["caseReference","Lien holdback control Reference","text","LSF07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1676250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2028263],["domainDriver","Distribution Class","select","Class member",["Class member","Lienholder","Counsel fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Settlement term library case","Claimant identity registry case","Eligibility validation case","Claim form ingestion case","Damage category calculation case"]}),
feature("attorney-fee-allocation","LSF08","Attorney fee allocation","Execute attorney fee allocation using settlement agreements, claimant eligibility, claim forms, damages, allocation formulas, liens, fees, taxes, distributions, returned payments, and residual funds.","Produce a governed attorney fee allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Settlement / Claimant Population","text","Settlement / Claimant Population · Standard Case"],["caseReference","Attorney fee allocation Reference","text","LSF08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1676250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2028263],["domainDriver","Distribution Class","select","Class member",["Class member","Lienholder","Counsel fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Settlement term library case","Claimant identity registry case","Eligibility validation case","Claim form ingestion case","Damage category calculation case"]}),
feature("administration-expense","LSF09","Administration expense","Execute administration expense using settlement agreements, claimant eligibility, claim forms, damages, allocation formulas, liens, fees, taxes, distributions, returned payments, and residual funds.","Produce a governed administration expense decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Settlement / Claimant Population","text","Settlement / Claimant Population · Standard Case"],["caseReference","Administration expense Reference","text","LSF09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1676250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2028263],["domainDriver","Distribution Class","select","Class member",["Class member","Lienholder","Counsel fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Settlement term library case","Claimant identity registry case","Eligibility validation case","Claim form ingestion case","Damage category calculation case"]}),
feature("tax-withholding-control","LSF10","Tax withholding control","Execute tax withholding control using settlement agreements, claimant eligibility, claim forms, damages, allocation formulas, liens, fees, taxes, distributions, returned payments, and residual funds.","Produce a governed tax withholding control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Settlement / Claimant Population","text","Settlement / Claimant Population · Standard Case"],["caseReference","Tax withholding control Reference","text","LSF10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1676250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2028263],["domainDriver","Distribution Class","select","Class member",["Class member","Lienholder","Counsel fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Settlement term library case","Claimant identity registry case","Eligibility validation case","Claim form ingestion case","Damage category calculation case"]}),
feature("distribution-file-generation","LSF11","Distribution file generation","Execute distribution file generation using settlement agreements, claimant eligibility, claim forms, damages, allocation formulas, liens, fees, taxes, distributions, returned payments, and residual funds.","Produce a governed distribution file generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Settlement / Claimant Population","text","Settlement / Claimant Population · Standard Case"],["caseReference","Distribution file generation Reference","text","LSF11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1676250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2028263],["domainDriver","Distribution Class","select","Class member",["Class member","Lienholder","Counsel fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Settlement term library case","Claimant identity registry case","Eligibility validation case","Claim form ingestion case","Damage category calculation case"]}),
feature("returned-payment-workflow","LSF12","Returned payment workflow","Execute returned payment workflow using settlement agreements, claimant eligibility, claim forms, damages, allocation formulas, liens, fees, taxes, distributions, returned payments, and residual funds.","Produce a governed returned payment workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Settlement / Claimant Population","text","Settlement / Claimant Population · Standard Case"],["caseReference","Returned payment workflow Reference","text","LSF12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1676250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2028263],["domainDriver","Distribution Class","select","Class member",["Class member","Lienholder","Counsel fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Settlement term library case","Claimant identity registry case","Eligibility validation case","Claim form ingestion case","Damage category calculation case"]}),
feature("residual-fund-calculation","LSF13","Residual fund calculation","Execute residual fund calculation using settlement agreements, claimant eligibility, claim forms, damages, allocation formulas, liens, fees, taxes, distributions, returned payments, and residual funds.","Produce a governed residual fund calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Settlement / Claimant Population","text","Settlement / Claimant Population · Standard Case"],["caseReference","Residual fund calculation Reference","text","LSF13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1676250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2028263],["domainDriver","Distribution Class","select","Class member",["Class member","Lienholder","Counsel fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Settlement term library case","Claimant identity registry case","Eligibility validation case","Claim form ingestion case","Damage category calculation case"]}),
feature("bank-reconciliation","LSF14","Bank reconciliation","Execute bank reconciliation using settlement agreements, claimant eligibility, claim forms, damages, allocation formulas, liens, fees, taxes, distributions, returned payments, and residual funds.","Produce a governed bank reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Settlement / Claimant Population","text","Settlement / Claimant Population · Standard Case"],["caseReference","Bank reconciliation Reference","text","LSF14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1676250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2028263],["domainDriver","Distribution Class","select","Class member",["Class member","Lienholder","Counsel fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Settlement term library case","Claimant identity registry case","Eligibility validation case","Claim form ingestion case","Damage category calculation case"]}),
feature("settlement-claimant-analytics","LSF15","Settlement claimant analytics","Execute settlement claimant analytics using settlement agreements, claimant eligibility, claim forms, damages, allocation formulas, liens, fees, taxes, distributions, returned payments, and residual funds.","Produce a governed settlement claimant analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Settlement / Claimant Population","text","Settlement / Claimant Population · Standard Case"],["caseReference","Settlement claimant analytics Reference","text","LSF15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1676250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2028263],["domainDriver","Distribution Class","select","Class member",["Class member","Lienholder","Counsel fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Settlement term library case","Claimant identity registry case","Eligibility validation case","Claim form ingestion case","Damage category calculation case"]})
]);
